TICKET_HEADER = "X-Udj-Ticket-Hash"
MISSING_RESOURCE_HEADER = "X-Udj-Missing-Resource"
CONFLICT_RESOURCE_HEADER = "X-Udj-Conflict-Resource"
MISSING_REASON_HEADER = "X-Udj-Missing-Reason"
PLAYER_PASSWORD_HEADER = "X-Udj-Player-Password"

DJANGO_TICKET_HEADER = "HTTP_X_UDJ_TICKET_HASH"
DJANGO_PLAYER_PASSWORD_HEADER = "HTTP_X_UDJ_PLAYER_PASSWORD"
