from udj.tests.tests06.auth import *
from udj.tests.tests06.server_capabilities import *
from udj.tests.tests06.favorite import *
from udj.tests.tests06.player_search import *
from udj.tests.tests06.user_creation import *
from udj.tests.tests06.player_creation import *
from udj.tests.tests06.player_administration import *
from udj.tests.tests06.player_interaction import *
from udj.tests.tests06.active_playlist import *
